# Generated by Django 4.2.16 on 2024-10-31 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
