# Generated by Django 4.2.16 on 2025-01-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_delete_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='heading_en_us',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='heading_ru',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
